// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cf6741e4-fec8-4ace-9291-5e8971f6f976",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vMLwE9Yqm",
    "aws_user_pools_web_client_id": "6lng6064c25etebnaavnra98g9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hmiogiobhjas3ivwdd2aqs6uqe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3s2b3orerrgyhn7wijgmdwzi4u",
    "aws_content_delivery_bucket": "amplifyapp-20190829191101-hostingbucket-test",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifyapp-20190829191101-hostingbucket-test.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
